### PR TITLE
Updated helpful message

### PR DESCRIPTION
**Pull request by OSOFAST**
Useful for platform using manifest.yml as the main deployment source.

### CODE REVIEW

**Comment by flavorjones** [comment]
Hi @OSOFAST,

Thanks so much for making this contribution. Can you verify that you're covered under a CLA, as @cfdreddbot requested?

This PR is surprisingly big, and I'd like some time to review it. Apologies for not responding earlier.

**Comment by OSOFAST** [comment]
Hi Mike,

The CLA has been signed and completed. I received a confirmation of
submission at some points as well.

Regards,
DB

**Comment by flavorjones** [comment]
OK, so it seems that this is big because it needs to be rebased. Once I did that, I see the relevant commit is b9eea86eed5af3e08e609fe99e7de4461e88ca7b.

**Comment by OSOFAST** [comment]
Hi Mike, sorry it was just a tiny comment in the message that I added,
would've saved me about 10 minutes of searching. Didn't know it was
combining all those other pulls like that

**Pull request closed without merging**
