### PR TITLE
Log on mismatch in md5 signature

### PR DESCRIPTION
**Pull request by sks**

### CODE REVIEW

**Comment by davidjahn** [comment]
Hi @sks , we think that this would be a useful error message to log in the compile-time messages. Could you possibly resubmit the error message to include
1. The file name that the md5 sum mismatched for
2. The expected md5
3. The actual md5

and we will be happy to merge. Thanks for your PR!

**Comment by sks** [comment]
@davidjahn : Honestly I forgot how this used to work :disappointed: 

We were creating a [custom buildpack](https://github.com/sks/staticfile-buildpack) based of static-buildpack , but using openresty instead and most of the time after compiling the modules, I forgot to change the md5 signature and the app deployment would fail with something like

```
Downloaded app package (182B)
Downloading build artifacts cache...
Downloaded build artifacts cache (129B)
Failed to compile droplet
Exit status 223

FAILED
BuildpackCompileFailed

```

I am not actively working on that buildpack, Sorry.

**Comment by davidjahn** [comment]
@sks No worries! We were just going through pull requests that we have not yet responded to. I will close the PR for now.

**Comment by sks** [comment]
Hey @davidjahn ,

I just added the rest of the string in https://github.com/cloudfoundry/compile-extensions/pull/8

**Pull request closed without merging**
